-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: schema/tables.json
-- Do not modify this file directly.

CREATE TABLE /*_*/starlight_review (
  sr_id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  sr_page_id INT UNSIGNED NOT NULL,
  sr_user_id INT UNSIGNED DEFAULT NULL,
  sr_session_token VARCHAR(64) DEFAULT NULL,
  sr_reviewer_name VARCHAR(50) NOT NULL,
  sr_rating SMALLINT UNSIGNED NOT NULL,
  sr_experience VARCHAR(200) DEFAULT NULL,
  sr_review_text TEXT DEFAULT NULL,
  sr_timestamp BINARY(14) NOT NULL,
  sr_modified BINARY(14) NOT NULL,
  sr_status VARCHAR(16) NOT NULL DEFAULT 'active',
  sr_ip_hash VARCHAR(64) DEFAULT NULL,
  sr_flags INT UNSIGNED NOT NULL DEFAULT 0,
  sr_verify_true INT UNSIGNED NOT NULL DEFAULT 0,
  sr_verify_mostly_true INT UNSIGNED NOT NULL DEFAULT 0,
  sr_verify_mixed INT UNSIGNED NOT NULL DEFAULT 0,
  sr_verify_mostly_false INT UNSIGNED NOT NULL DEFAULT 0,
  sr_verify_false INT UNSIGNED NOT NULL DEFAULT 0,
  sr_verify_inconclusive INT UNSIGNED NOT NULL DEFAULT 0,
  sr_verify_score DECIMAL(5,2) NOT NULL DEFAULT 0,
  sr_verify_locked SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  sr_sort_score DECIMAL(5,4) NOT NULL DEFAULT 0,
  sr_outdated_count INT UNSIGNED NOT NULL DEFAULT 0
) /*$wgDBTableOptions*/;

CREATE INDEX sr_page ON /*_*/starlight_review (sr_page_id);
CREATE INDEX sr_user ON /*_*/starlight_review (sr_user_id);
CREATE INDEX sr_session ON /*_*/starlight_review (sr_session_token);
CREATE INDEX sr_page_status_time ON /*_*/starlight_review (sr_page_id, sr_status, sr_timestamp);
CREATE INDEX sr_page_status_sort ON /*_*/starlight_review (sr_page_id, sr_status, sr_sort_score);
CREATE INDEX sr_ip ON /*_*/starlight_review (sr_ip_hash);

CREATE TABLE /*_*/starlight_review_log (
  srl_id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  srl_review_id INT UNSIGNED NOT NULL,
  srl_actor_id INT UNSIGNED NOT NULL,
  srl_action VARCHAR(32) NOT NULL,
  srl_reason VARCHAR(500) DEFAULT NULL,
  srl_timestamp BINARY(14) NOT NULL,
  srl_data BLOB DEFAULT NULL
) /*$wgDBTableOptions*/;

CREATE INDEX srl_review ON /*_*/starlight_review_log (srl_review_id);
CREATE INDEX srl_actor ON /*_*/starlight_review_log (srl_actor_id);
CREATE INDEX srl_timestamp ON /*_*/starlight_review_log (srl_timestamp);

CREATE TABLE /*_*/starlight_page_stats (
  sps_page_id INT UNSIGNED NOT NULL PRIMARY KEY,
  sps_review_count INT UNSIGNED NOT NULL DEFAULT 0,
  sps_avg_rating DECIMAL(3,2) NOT NULL DEFAULT 0,
  sps_rating_1 INT UNSIGNED NOT NULL DEFAULT 0,
  sps_rating_2 INT UNSIGNED NOT NULL DEFAULT 0,
  sps_rating_3 INT UNSIGNED NOT NULL DEFAULT 0,
  sps_rating_4 INT UNSIGNED NOT NULL DEFAULT 0,
  sps_rating_5 INT UNSIGNED NOT NULL DEFAULT 0,
  sps_updated BINARY(14) NOT NULL
) /*$wgDBTableOptions*/;

CREATE TABLE /*_*/starlight_verification (
  sv_id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  sv_review_id INT UNSIGNED NOT NULL,
  sv_user_id INT UNSIGNED NOT NULL,
  sv_verdict VARCHAR(16) NOT NULL,
  sv_timestamp BINARY(14) NOT NULL,
  sv_weight DECIMAL(3,2) NOT NULL DEFAULT 1
) /*$wgDBTableOptions*/;

CREATE UNIQUE INDEX sv_review_user ON /*_*/starlight_verification (sv_review_id, sv_user_id);
CREATE INDEX sv_review_verdict ON /*_*/starlight_verification (sv_review_id, sv_verdict);
CREATE INDEX sv_user_time ON /*_*/starlight_verification (sv_user_id, sv_timestamp);

CREATE TABLE /*_*/starlight_outdated (
  so_id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  so_review_id INT UNSIGNED NOT NULL,
  so_user_id INT UNSIGNED NOT NULL,
  so_timestamp BINARY(14) NOT NULL
) /*$wgDBTableOptions*/;

CREATE UNIQUE INDEX so_review_user ON /*_*/starlight_outdated (so_review_id, so_user_id);
CREATE INDEX so_review ON /*_*/starlight_outdated (so_review_id);
